### ISSUE TITLE
Currently there is only 1 chart and it cannot handle more than 79 groups due to the its maximum number of columns

### ISSUE THREAD

**Issue by miketvo** [kuri-team/rmit-cosc2081-assignment#11]
Currently there is only 1 chart and it cannot handle more than 79 groups due to the its maximum number of columns.

Need to ask Dr. Tri about this.

_Originally posted by @rider3458 in https://github.com/kuri-team/rmit-cosc2081-assignment/issues/9#issuecomment-898145429_

**Comment by rider3458** [comment]
Solution: display an error message when the user wants to display the chart with more than 79 groups.

**Comment by miketvo** [comment]
Resolved
